presets:
  workstation: [base, shell, dev-c, dev-python, dev-node]
  server: [base, shell, dev-python, dev-node]
  hpc: [shell-hpc]

hosts:
  blanc:
    preset: workstation
    user: blank
    ssh_host: blanc
  everest:
    preset: workstation
    user: blank
    ssh_host: everest
  campbell:
    preset: server
    user: blank
    ssh_host: campbell
  granite:
    preset: workstation
    extra: [apps-docker]
    user: blank
    ssh_host: granite
  pioneer:
    preset: hpc
    user: axj770
    ssh_host: pioneer.case.edu
    aliases: [hpc5, hpc6, hpc7, hpc8, hpctransfer1]
    hpc:
      scratch: /scratch/pioneer/users/axj770
      lmod_pkg: /usr/local/lmod/lmod
      modules: [GCCcore/13.2.0, git/2.42.0-GCCcore-13.2.0, Python/3.11.5-GCCcore-13.2.0]
